# Generated by Django 5.0.1 on 2024-01-28 20:29

import json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('comida', '0001_initial'),
    ]
    def insert_data(self, schema_editor):
        categoria_model = self.get_model('categoria', 'Categoria')
        comida = self.get_model('comida', 'Comida')
        producto_model = self.get_model('producto', 'Producto')
        with open('data.json') as f:
            data = json.load(f)
            for tipo_comida, categorias in data.items():
                for categoria, productos in categorias.items():
                    comida_instance = comida.objects.get(nombre=tipo_comida)
                    categoria_instance = categoria_model.objects.get(nombre=categoria, comida=comida_instance)
                    for producto in productos:
                        producto_model.objects.create(nombre=producto["producto"], precio=producto["precio"], categoria=categoria_instance, comida=comida_instance)
    
                    
    def undo_insert_data(self, schema_editor):
        model = self.get_model('producto', 'Producto')
        model.objects.all().delete()
        
    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comida.comida')),
            ],
        ),
        migrations.RunPython(insert_data,reverse_code=undo_insert_data)
    ]
