# Generated by Django 5.0.1 on 2024-01-27 00:10

import json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    def insert_init_data(self, schema_editor):
        comida = self.get_model('comida', 'Comida')
        with open('data.json') as f:
            data = json.load(f)
            for tipo_comida, categorias in data.items():
                comida.objects.create(nombre=tipo_comida)
                
    def undo_insert_data(self, schema_editor):
        comida = self.get_model('comida', 'Comida')
        comida.objects.all().delete()
            
    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RunPython(insert_init_data,reverse_code=undo_insert_data)
    ]
